### ISSUE TITLE
🚀 Feature Request:  DefaultSymbols variant

### ISSUE THREAD

**Issue by DanDeepPhase** [cmichelenstrofer/DimensionfulAngles.jl#15]
## Feature Request
Unitful has a submodule that allows spamming lots of types into active environment, eliminating the need for the `u"  "` syntax.
```julia 
using Unitful
using Unitful.DefaultSymbols
a = 5mm
```
A variant of that code (perhaps `DimensionfulAngles.DefaultSymbols`) would be another usage variant (similar to # 3 in the readme.md), that would operate like Unitful, but with dimensions. What I'm thinking is to replicate that module, but export dimensionful angles in place of the non-dimensional angles from Unitful. Then it would be almost the same as using Unitful directly, but with the benefit of a dimension behind the scenes. It feels a bit cheating... like almost type piracy? but it is explicitly called and requires the submodule to be used, so should be safe from a code perspective.

The module is in 
https://github.com/PainterQubits/Unitful.jl/blob/5cf162734af3c90c16425346d9f0d020d19f23f3/src/pkgdefaults.jl#L711-L731. I see degrees in the last two lines, but not sure where rad and sr are imported.  
```julia
baremodule DefaultSymbols
    import Unitful

    for u in (:𝐋,:𝐌,:𝐓,:𝐈,:𝚯,:𝐉,:𝐍)
        Core.eval(DefaultSymbols, Expr(:import, Expr(:(.), :Unitful, u)))
        Core.eval(DefaultSymbols, Expr(:export, u))
    end

    for p in Unitful.si_prefixes
        for u in Unitful.si_no_prefix
            Core.eval(DefaultSymbols, Expr(:import, Expr(:(.), :Unitful, Symbol(p,u))))
            Core.eval(DefaultSymbols, Expr(:export, Symbol(p,u)))
        end
    end

    Core.eval(DefaultSymbols, Expr(:import, Expr(:(.), :Unitful, :°C)))
    Core.eval(DefaultSymbols, Expr(:export, :°C))

    Core.eval(DefaultSymbols, Expr(:import, Expr(:(.), :Unitful, :°)))
    Core.eval(DefaultSymbols, Expr(:export, :°))
end
```

## Interested in leading the development of this feature?
- 🚀 Yes! I can lead the development of this feature.

**Comment by cmichelenstrofer** [comment]
Great idea! And I agree with you that this should be fine since it is explicitly called. If it is piracy, then technically so is *Option 3* in the README.md. We could add a note/warning that using these options can have unintended side effects if you also use another package that expects rad/degree to be dimensionless.

**Comment by cmichelenstrofer** [comment]
> I see degrees in the last two lines, but not sure where rad and sr are imported.

`rad` and `sr` are specified in the `Unitful.si_no_prefix` on [line 708](https://github.com/PainterQubits/Unitful.jl/blob/5cf162734af3c90c16425346d9f0d020d19f23f3/src/pkgdefaults.jl#L708) and then are evaluated inside the `DefaultSymbols` module on [line 722](https://github.com/PainterQubits/Unitful.jl/blob/5cf162734af3c90c16425346d9f0d020d19f23f3/src/pkgdefaults.jl#L722). All prefixed versions are evaluated. Lines 705-709 (right before the code snipet you shared):

```julia
const si_prefixes = (:y, :z, :a, :f, :p, :n, :μ, :m, :c, :d,
    Symbol(""), :da, :h, :k, :M, :G, :T, :P, :E, :Z, :Y)

const si_no_prefix = (:m, :s, :A, :K, :g, :mol, :rad, :sr, :Hz, :N, :Pa, #:cd,
    :J, :W, :C, :V, :F, :Ω, :S, :Wb, :T, :H, :lm, :lx, :Bq, :Gy, :Sv, :kat)
```
